goshell:
  version: "0.0.1-SNAPSHOT-1"
  server:
    port: 8080


kafka:
  bootstrapServers: "kafka1:9092,kafka2:9093"
  producers:
    results:
      topic: "trooper-scripts-results"
  consumers:
    -
      topic: "trooper-cep-results"


cassandra:
  hosts: "cassdb:9042"
  keyspace: "goshell"