goshell:
  version: "0.0.1-SNAPSHOT-1"
  server:
    port: 8080


kafka:
  bootstrapServers: "localhost:29092"
  results:
    producers:
      topic: "trooper-scripts-results"
  consumers:  
    -
      topic: "trooper-scripts-results"


cassandra:
  hosts: "localhost:9042"
  keyspace: "goshell"